env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
ignorePatterns:
  - vite.config.ts
rules:
  # Reactのインポートをチェックしない
  react/react-in-jsx-scope: off
